# Generated by Django 2.1.7 on 2019-03-14 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20190306_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='uploadpaste', max_length=10)),
                ('privacy', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('content', models.FileField(upload_to='.')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Enabled', max_length=10)),
                ('expiry', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadpaste_requests_created', to=settings.AUTH_USER_MODEL)),
                ('invited_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paste',
            name='category',
            field=models.CharField(default='paste', max_length=10),
        ),
    ]
