# Generated by Django 2.1.7 on 2019-03-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190314_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='category',
        ),
        migrations.RemoveField(
            model_name='uploadpaste',
            name='category',
        ),
        migrations.AlterField(
            model_name='uploadpaste',
            name='content',
            field=models.FileField(upload_to=''),
        ),
    ]
