# Generated by Django 2.1.7 on 2019-03-14 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('keyword1', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('keyword2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('keyword3', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
